name: QA IMAGE BUILD

on:
  push:
    branches:
      - main
      - qa-main
  workflow_dispatch:

env:
  EKS_CLUSTER_NAME: shothik-prod
  AWS_REGION: us-east-1

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: "."
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ridz-shothikai
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: 'Set Short Commit Hash'
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV


      - name: "Build And Push Image"
        run: |
          docker build --no-cache \
          --tag ghcr.io/ridz-shothikai/shothik-v2:${{ env.SHORT_SHA }} \
          --build-arg GITHUB_PAT=${{ secrets.ACCESS_TOKEN }} \
          --build-arg NEXT_PUBLIC_SOCKET=http://163.172.172.38:8080 \
          --build-arg NEXT_PUBLIC_API_URI=http://163.172.172.38:8080/api \
          --build-arg NEXT_PUBLIC_DOMAIN_URI=http://163.172.172.38:3000 \
          --build-arg NEXT_PUBLIC_GOOGLE_CLIENT_ID="259331281661-14jks3qs71c27j5h7t2jf7uc6c0d4lm1.apps.googleusercontent.com" \
          .
          docker push ghcr.io/ridz-shothikai/shothik-v2:${{ env.SHORT_SHA }}